(()=>{const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];let opened=false,journey=true;
function enhance(){
 if(!q('#fullscreen-envelope-v10'))document.head.insertAdjacentHTML('beforeend',`<style id="fullscreen-envelope-v10">
.intro{position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;min-height:100svh!important;background:#061b34!important;overflow:hidden!important;perspective:1800px!important;isolation:isolate}.intro:before{content:"";position:absolute!important;inset:0!important;background:radial-gradient(circle at 50% 42%,rgba(42,91,139,.34),transparent 42%),repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 1px,transparent 1px 9px)!important;z-index:0!important;pointer-events:none}.intro:after{content:"";position:absolute;inset:0;z-index:1;pointer-events:none;background:linear-gradient(145deg,transparent 0 14%,rgba(209,170,115,.11) 14.1% 14.25%,transparent 14.35% 85.5%,rgba(209,170,115,.08) 85.65% 85.8%,transparent 85.9%)}
.introcopy{position:absolute!important;z-index:18!important;top:clamp(48px,8vh,96px)!important;left:5vw!important;right:5vw!important;text-align:center!important;pointer-events:none}.introcopy small{display:block!important;color:#d6b77c!important;opacity:.9!important;font-size:clamp(8px,1.8vw,12px)!important;letter-spacing:.38em!important}.introcopy h1{margin:clamp(18px,3vh,34px) 0 8px!important;color:#f6e7c6!important;font:500 clamp(46px,9vw,96px)/.83 var(--serif)!important;letter-spacing:-.035em!important;text-shadow:0 5px 22px #0009!important}.introcopy h1:after{content:"";display:block;width:min(38vw,240px);height:1px;margin:clamp(16px,2.2vh,24px) auto 0;background:linear-gradient(90deg,transparent,#cba66e,transparent)}.introcopy em{display:block!important;color:#e0c38e!important;opacity:.94!important;font:500 clamp(10px,2vw,14px)/1.6 var(--sans)!important;letter-spacing:.25em!important;text-transform:uppercase!important}.introcopy em:after{content:"LOVE · FAITH · A BEAUTIFUL FUTURE";display:block;margin-top:clamp(10px,1.6vh,18px);font:500 clamp(6px,1.3vw,9px) var(--sans);letter-spacing:.32em;color:#b79862;opacity:.8}
.stage{position:absolute!important;inset:0!important;left:0!important;top:0!important;width:100vw!important;height:100dvh!important;transform:none!important;z-index:5!important;transform-style:preserve-3d!important}.envelope{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;filter:none!important;transform-style:preserve-3d!important}.back{position:absolute!important;inset:0!important;border-radius:0!important;background:linear-gradient(160deg,#0d3158,#071c35 58%,#041225)!important;border:0!important;box-shadow:none!important}.foldl,.foldr,.foldb,.flap{position:absolute!important;border-radius:0!important;background-color:#0a2a4b!important;background-image:radial-gradient(circle at 20% 22%,rgba(220,187,128,.04) 0 1px,transparent 1.6px),repeating-linear-gradient(135deg,rgba(255,255,255,.02) 0 1px,transparent 1px 9px),linear-gradient(145deg,#123f70,#092a4e 58%,#061a32)!important;box-shadow:inset 0 0 0 1px rgba(209,170,115,.07)!important}.foldl{left:0!important;bottom:0!important;width:58%!important;height:58%!important;clip-path:polygon(0 0,100% 52%,100% 100%,0 100%)!important}.foldr{right:0!important;bottom:0!important;width:58%!important;height:58%!important;clip-path:polygon(0 52%,100% 0,100% 100%,0 100%)!important}.foldb{left:0!important;right:0!important;bottom:0!important;height:47%!important;clip-path:polygon(0 100%,50% 0,100% 100%)!important;background-image:repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 1px,transparent 1px 9px),linear-gradient(165deg,#0f365f,#071f3c)!important}.flap{left:0!important;right:0!important;top:0!important;height:58%!important;clip-path:polygon(0 0,50% 88%,100% 0)!important;transform-origin:50% 0!important;backface-visibility:hidden!important;z-index:12!important;background-image:radial-gradient(circle at 18% 15%,rgba(209,170,115,.06),transparent 25%),repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 1px,transparent 1px 9px),linear-gradient(165deg,#123f70,#092a4e 65%,#061a32)!important;filter:drop-shadow(0 18px 24px rgba(0,0,0,.32))}.flap:after{content:"";position:absolute;left:0;right:0;bottom:0;height:1px;background:linear-gradient(90deg,transparent,#d0a869 18%,#efd49e 50%,#d0a869 82%,transparent);opacity:.72}
.seal{position:absolute!important;left:50%!important;top:58%!important;z-index:22!important;width:clamp(108px,17vw,156px)!important;height:clamp(108px,17vw,156px)!important;transform:translate(-50%,-50%)!important;border:2px solid rgba(235,203,142,.48)!important;border-radius:50%!important;color:#f6deb0!important;background:radial-gradient(circle at 34% 27%,#d5ae67,#a67632 36%,#77511e 64%,#4d3112)!important;box-shadow:inset 0 0 0 7px rgba(255,232,185,.12),inset 0 0 0 16px rgba(48,28,7,.18),0 22px 45px rgba(0,0,0,.55),0 0 0 1px rgba(246,214,157,.22)!important;font:500 clamp(27px,4vw,40px) var(--serif)!important;letter-spacing:.08em!important;text-shadow:0 2px 5px #3a210e!important;cursor:pointer!important}.seal:before{inset:-16px!important;border:1px solid rgba(224,190,127,.46)!important;animation:pulse 2.4s ease-in-out infinite!important}.seal:after{content:"TAP TO OPEN"!important;top:calc(100% + clamp(34px,5vh,54px))!important;color:#d8bb83!important;font:600 clamp(8px,1.7vw,12px) var(--sans)!important;letter-spacing:.35em!important;text-shadow:none!important}
.letter{position:absolute!important;z-index:7!important;left:50%!important;top:57%!important;width:min(82vw,620px)!important;height:min(72dvh,760px)!important;right:auto!important;bottom:auto!important;transform:translate(-50%,-45%) scale(.82)!important;opacity:0!important;pointer-events:none!important;border-radius:24px!important;overflow:hidden!important;transition:transform 1.7s cubic-bezier(.16,1,.3,1),opacity .8s ease!important}.photo-invite{height:100%!important;width:100%!important;border-radius:24px!important;box-shadow:0 36px 90px rgba(0,0,0,.52)!important;grid-template-rows:52% 48%!important}.invite-photo img{object-position:center 30%!important}.intro.red-opened .flap{transform:rotateX(178deg)!important;transition:transform 1.25s cubic-bezier(.16,1,.3,1)!important}.intro.red-opened .seal{transform:translate(-50%,-50%) scale(.82)!important;opacity:0!important;transition:transform .6s ease,opacity .45s ease!important}.intro.red-opened .letter{z-index:20!important;opacity:1!important;transform:translate(-50%,-49%) scale(1)!important;transition-delay:.55s!important}.intro.red-opened .introcopy{opacity:0!important;transform:translateY(-20px)!important;transition:.65s ease!important}.intro.red-opened .foldl,.intro.red-opened .foldr,.intro.red-opened .foldb{filter:brightness(.72)!important;transition:filter .8s ease!important}
@media(max-width:760px){.introcopy{top:5.5vh!important}.introcopy h1{font-size:clamp(42px,12vw,66px)!important}.stage{height:100dvh!important}.flap{height:59%!important}.foldl,.foldr{height:59%!important}.foldb{height:47%!important}.seal{top:59%!important;width:118px!important;height:118px!important;font-size:31px!important}.letter{width:88vw!important;height:74dvh!important;top:57%!important}.photo-invite{grid-template-rows:49% 51%!important}.invite-paper .lux-names{font-size:20px!important}.invite-paper .lux-copy{font-size:7.5px!important}.invite-paper .lux-details{font-size:4.2px!important}}
@media(max-width:430px){.introcopy{top:4.5vh!important}.introcopy small{font-size:7px!important}.introcopy h1{font-size:44px!important}.introcopy em{font-size:8px!important}.seal{top:60%!important;width:108px!important;height:108px!important;font-size:28px!important}.letter{width:90vw!important;height:72dvh!important}.photo-invite{grid-template-rows:47% 53%!important}}
@media(max-height:700px){.introcopy{top:3vh!important}.introcopy h1{font-size:38px!important;margin:10px 0 5px!important}.introcopy em:after{margin-top:5px!important}.seal{top:60%!important;width:96px!important;height:96px!important}.letter{height:78dvh!important}}
</style>`);
 const letter=q('.letter');if(letter&&!q('.photo-invite',letter)){letter.innerHTML='<div class="lux-invite photo-invite"><div class="invite-photo"><img src="https://drive.google.com/thumbnail?id=1o3ESuqFtG9MM2-4tPu5BINiB1AH_OTSI&sz=w1600" alt="Dr Martin and Pearl"><div class="photo-vignette"></div><div class="photo-mark">M <i>&amp;</i> P</div></div><div class="invite-paper"><div class="botanical b1">❧</div><div class="botanical b2">❧</div><div class="foil-frame"></div><div class="lux-kicker">Together with their families</div><div class="lux-names">Dr Martin <em>&amp;</em> Pearl</div><div class="lux-copy">request the honour of your presence<br>as they begin forever</div><div class="lux-rule"><i></i><b>22 · 12 · 26</b><i></i></div><div class="lux-details"><span>10:00 AM · St. Mary’s Cathedral Rubaga</span><span>By His Grace Archbishop Paul Ssemogerere</span><span>2:30 PM · Reception · Mutima Hall</span></div><div class="lux-signoff">Kampala, Uganda</div></div><div class="vellum-sheen"></div></div>'}
 if(!q('#journeyHud'))document.body.insertAdjacentHTML('beforeend','<div id="journeyHud"><i></i><span>Journey · playing</span></div><div id="magicLayer" aria-hidden="true"></div><div id="loveEcho" aria-hidden="true"><span>M</span><i>♥</i><span>P</span></div><div id="chapterMeter" aria-hidden="true"></div>');
 const hud=q('#journeyHud'),magic=q('#magicLayer'),echo=q('#loveEcho'),meter=q('#chapterMeter');if(hud)hud.onclick=()=>{journey=!journey;hud.querySelector('span').textContent=journey?'Journey · playing':'Journey · paused'};
 const tl=q('.timelinegrid');if(tl)tl.innerHTML='<div><b>10:00 AM</b><span>Church ceremony</span></div><div><b>2:30 PM</b><span>Reception</span></div><div><b>4:00 PM</b><span>Dinner</span></div><div><b>6:00 PM</b><span>Cake</span></div>';
 const cathedral=q('.cathedral-cinema');if(cathedral&&!q('.officiant-note',cathedral)){const target=q('.cathedral-copy,.cathedral-content,.gatecopy,.venuecontent',cathedral)||cathedral;target.insertAdjacentHTML('beforeend','<p class="officiant-note">10:00 AM · Holy Matrimony<br><strong>By His Grace Archbishop Paul Ssemogerere</strong></p>')}
 qa('.venue.church .venuecontent').forEach(v=>{if(!q('.officiant-note',v))v.insertAdjacentHTML('beforeend','<p class="officiant-note">10:00 AM · By His Grace Archbishop Paul Ssemogerere</p>')});
 const chapters=qa('.chapter'),words=['The beginning','You & me','A thousand little moments','Home is you','Forever starts here'];chapters.forEach((c,i)=>{if(!q('.cinema-light',c))c.insertAdjacentHTML('beforeend','<div class="cinema-light"></div>');if(!q('.chapter-whisper',c))c.insertAdjacentHTML('beforeend',`<div class="chapter-whisper">${words[i]||'Always'}</div>`);if(!q('.page-number',c))c.insertAdjacentHTML('beforeend',`<div class="page-number">0${i+1} / 05</div>`);if(i===0)c.classList.add('curtain-scene');if(i===3&&!q('.ring-moment',c))c.insertAdjacentHTML('beforeend','<div class="ring-moment"></div>')});
 function burst(x,y,n=9){if(!magic)return;for(let i=0;i<n;i++){const s=document.createElement('b');s.className='magic-spark';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',(Math.random()*130-65)+'px');s.style.setProperty('--y',(Math.random()*-120-20)+'px');magic.appendChild(s);setTimeout(()=>s.remove(),1800)}}
 function heartRain(){if(!magic)return;for(let i=0;i<14;i++){const h=document.createElement('em');h.className='love-drop';h.textContent=Math.random()>.45?'✦':'♡';h.style.left=(5+Math.random()*90)+'vw';h.style.animationDelay=(Math.random()*1.4)+'s';h.style.animationDuration=(4+Math.random()*3)+'s';magic.appendChild(h);setTimeout(()=>h.remove(),8000)}}
 const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('cinema-seen');const i=chapters.indexOf(e.target);if(i>=0&&meter){meter.textContent=`Chapter ${i+1} · ${words[i]}`;meter.classList.add('show');setTimeout(()=>meter.classList.remove('show'),2200);if(i===2)heartRain();if(i===4&&echo){echo.classList.add('show');setTimeout(()=>echo.classList.remove('show'),3500)}}}}),{threshold:.5});chapters.forEach(c=>revealObs.observe(c));
 const seal=q('.seal');if(seal)seal.addEventListener('click',()=>{opened=true;document.body.classList.add('opened','lux-opened');q('.intro')?.classList.add('red-opened');journey=true;burst(innerWidth/2,innerHeight*.59,18);setTimeout(heartRain,900);setTimeout(()=>requestAnimationFrame(autoJourney),2600)},{once:true});
 ['touchstart','wheel','pointerdown'].forEach(ev=>addEventListener(ev,e=>{if(!opened||e.target.closest?.('#journeyHud'))return;journey=false;if(hud)hud.querySelector('span').textContent='Journey · paused'},{passive:true}));
 function autoJourney(){if(opened&&journey){const el=document.elementFromPoint(innerWidth/2,innerHeight*.62);let speed=1.18;if(el?.closest('.chapter'))speed=1.34;if(el?.closest('.cathedral-cinema'))speed=.92;if(el?.closest('.venues'))speed=.98;if(el?.closest('.actions'))speed=.76;scrollBy(0,speed)}requestAnimationFrame(autoJourney)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();})();