(()=>{const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];let opened=false,journey=true,raf;
function enhance(){
 document.body.insertAdjacentHTML('beforeend','<div id="journeyHud"><i></i><span>Journey · playing</span></div><div id="magicLayer" aria-hidden="true"></div><div id="loveEcho" aria-hidden="true"><span>M</span><i>♥</i><span>P</span></div><div id="chapterMeter" aria-hidden="true"></div>');
 const hud=q('#journeyHud'),magic=q('#magicLayer'),echo=q('#loveEcho'),meter=q('#chapterMeter');hud.onclick=()=>{journey=!journey;hud.querySelector('span').textContent=journey?'Journey · playing':'Journey · paused'};
 const tl=q('.timelinegrid');if(tl)tl.innerHTML='<div><b>10:00 AM</b><span>Church ceremony</span></div><div><b>2:30 PM</b><span>Reception</span></div><div><b>4:00 PM</b><span>Dinner</span></div><div><b>6:00 PM</b><span>Cake</span></div>';
 const cathedral=q('.cathedral-cinema');if(cathedral&&!q('.officiant-note',cathedral)){const target=q('.cathedral-copy,.cathedral-content,.gatecopy,.venuecontent',cathedral)||cathedral;target.insertAdjacentHTML('beforeend','<p class="officiant-note">10:00 AM · Holy Matrimony<br><strong>By His Grace Archbishop Paul Ssemogerere</strong></p>')}
 qa('.venue.church .venuecontent').forEach(v=>{if(!q('.officiant-note',v))v.insertAdjacentHTML('beforeend','<p class="officiant-note">10:00 AM · By His Grace Archbishop Paul Ssemogerere</p>')});
 const chapters=qa('.chapter'),words=['The beginning','You & me','A thousand little moments','Home is you','Forever starts here'];chapters.forEach((c,i)=>{if(!q('.cinema-light',c))c.insertAdjacentHTML('beforeend','<div class="cinema-light"></div>');if(!q('.chapter-whisper',c))c.insertAdjacentHTML('beforeend',`<div class="chapter-whisper">${words[i]||'Always'}</div>`);if(!q('.page-number',c))c.insertAdjacentHTML('beforeend',`<div class="page-number">0${i+1} / 05</div>`);if(i===0)c.classList.add('curtain-scene');if(i===3&&!q('.ring-moment',c))c.insertAdjacentHTML('beforeend','<div class="ring-moment"></div>')});
 function burst(x,y,n=9){for(let i=0;i<n;i++){const s=document.createElement('b');s.className='magic-spark';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--x',(Math.random()*130-65)+'px');s.style.setProperty('--y',(Math.random()*-120-20)+'px');s.style.animationDelay=(Math.random()*.12)+'s';magic.appendChild(s);setTimeout(()=>s.remove(),1900)}}function heartRain(){for(let i=0;i<16;i++){const h=document.createElement('em');h.className='love-drop';h.textContent=Math.random()>.45?'✦':'♡';h.style.left=(5+Math.random()*90)+'vw';h.style.animationDelay=(Math.random()*1.4)+'s';h.style.animationDuration=(4+Math.random()*3)+'s';magic.appendChild(h);setTimeout(()=>h.remove(),8000)}}
 addEventListener('pointerdown',e=>{if(opened&&!e.target.closest('#journeyHud'))burst(e.clientX,e.clientY,6)},{passive:true});const revealObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('cinema-seen');const i=chapters.indexOf(e.target);if(i>=0){meter.textContent=`Chapter ${i+1} · ${words[i]}`;meter.classList.add('show');setTimeout(()=>meter.classList.remove('show'),2200);if(i===2)heartRain();if(i===4){echo.classList.add('show');setTimeout(()=>echo.classList.remove('show'),3500)}}const r=e.target.getBoundingClientRect();if(Math.random()>.35)burst(innerWidth*.5,Math.min(innerHeight*.75,Math.max(100,r.top+innerHeight*.35)),7)}}),{threshold:.5});chapters.forEach(c=>revealObs.observe(c));const venueObs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){document.body.classList.add('venue-awake');heartRain();setTimeout(()=>document.body.classList.remove('venue-awake'),5000)}}),{threshold:.55});qa('.cathedral-cinema,.venues').forEach(v=>venueObs.observe(v));
 if(tl){const obs=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const r=e.target.getBoundingClientRect(),p=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height)));e.target.style.setProperty('--timeline',p*100+'%');[...e.target.children].forEach((k,i,a)=>k.classList.toggle('timeline-lit',p>(i+1)/(a.length+1)))}),{threshold:[0,.1,.25,.5,.75,1]});obs.observe(tl)}const seal=q('.seal');if(seal)seal.addEventListener('click',()=>{opened=true;document.body.classList.add('opened');journey=true;burst(innerWidth/2,innerHeight*.58,18);setTimeout(heartRain,900);setTimeout(()=>requestAnimationFrame(autoJourney),2500)},{once:true});['touchstart','wheel','pointerdown'].forEach(ev=>addEventListener(ev,e=>{if(!opened||e.target.closest?.('#journeyHud'))return;journey=false;const h=q('#journeyHud span');if(h)h.textContent='Journey · paused'},{passive:true}));function autoJourney(){if(opened&&journey){const el=document.elementFromPoint(innerWidth/2,innerHeight*.62);let speed=1.18;if(el?.closest('.chapter'))speed=1.34;if(el?.closest('.cathedral-cinema'))speed=.92;if(el?.closest('.venues'))speed=.98;if(el?.closest('.actions'))speed=.76;scrollBy(0,speed)}raf=requestAnimationFrame(autoJourney)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();})();