(()=>{
'use strict';
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const DRIVE_IDS=[
'1RVfbarYJg3p7SZjeiFIHq2PrY2V26aLH','1o3ESuqFtG9MM2-4tPu5BINiB1AH_OTSI','1Yc5KV4QLBDPW7_AbMsua2c639_j2a64q','1ZCCpWXnBzGxrwkQTqdA0ULmw07rg3qXr','1trAhd8ztTuWpWIX0m2QEmdLlLFIb7BCN','1YBf3V8S_7WwXl4PZa-Ay16xg8kQEbgpt','1veT3F-5LedP7EmvdnxichO11pFQR27EI','1gBpU-xcqlgaRQPaFfLRlqxqbSEGYYpgL','1ZRnAXHUMuEfF8nIigfRlCYfa797lESRw','1LJDUZ9lgGPVqPlamYxEjcjZ5wIZhKSK2','1y7GBwCcsG-j-tO4QE6kLDyKuCNRCJEQE','1fIM4VjAf2rD_XacwO5Z1zZOwFFgdTeRi','1lgd7mSvXL-KNj8EnmoDYT66VqStcUMBP','1PUOQWqoA-9o_W1gdJNcT0URqXJTX6btP'];
const drive=id=>`https://drive.google.com/thumbnail?id=${id}&sz=w1800`;
const HOLD=3200;
const scenes=[
 {big:'What is love?',small:'Perhaps it begins quietly.',kind:'question',rose:true},
 {big:'A glance that stays.',small:'A hand that begins to feel like home.',kind:'split'},
 {big:'Two lives choosing one another.',small:'Again. And again.',kind:'words'},
 {big:'Until forever stops sounding far away.',small:'And starts sounding like us.',kind:'sweep',rose:true},
 {big:'You are invited.',small:'22 · 12 · 2026',kind:'hero'},
 {big:'Now… about these two.',small:'They met. Nobody announced, “this is forever.”',kind:'fun'},
 {big:'It was probably meant to be casual.',small:'Then one conversation somehow needed another.',kind:'tilt'},
 {big:'Then another.',small:'And suddenly “see you sometime” became “when are we meeting?”',kind:'pop'},
 {big:'The funny thing about forever…',small:'It rarely introduces itself properly.',kind:'script',rose:true},
 {big:'It just keeps showing up.',small:'In laughter. In patience. In choosing each other.',kind:'words'},
 {big:'So they chose a date.',small:'Tuesday · 22 December 2026',kind:'date'},
 {big:'First, the promise.',small:'10:00 AM · St. Mary’s Cathedral Rubaga',kind:'church'},
 {big:'With a special blessing.',small:'Holy Matrimony by His Grace Archbishop Paul Ssemogerere',kind:'church'},
 {big:'Then… we celebrate.',small:'2:30 PM · Reception · Mutima Hall',kind:'party'},
 {big:'Come hungry.',small:'4:00 PM · Dinner',kind:'fun'},
 {big:'And save room.',small:'6:00 PM · Cake',kind:'cake'},
 {big:'Bring your best smile.',small:'The rest of the evening belongs to music, family & joy.',kind:'party'},
 {program:true,kind:'program'}
];
function addStyles(){if(q('#loveJourneyStyle'))return;const s=document.createElement('style');s.id='loveJourneyStyle';s.textContent=`
#fullEnvelopeLanding{position:fixed;inset:0;z-index:1000;width:100vw;height:100dvh;min-height:100svh;overflow:hidden;background:#082746;color:#f4dfb3;font-family:'DM Sans',sans-serif;perspective:1900px;isolation:isolate;-webkit-tap-highlight-color:transparent}
#fullEnvelopeLanding:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 36%,rgba(53,111,164,.28),transparent 43%),repeating-linear-gradient(135deg,rgba(255,255,255,.025) 0 1px,transparent 1px 9px);pointer-events:none}
.fe-corner{position:absolute;z-index:10;width:clamp(110px,26vw,210px);height:clamp(110px,26vw,210px);opacity:.48;pointer-events:none;filter:drop-shadow(0 0 9px #d6b87925)}.fe-corner:before,.fe-corner:after{content:"";position:absolute;border-color:#d5b577;border-style:solid;border-width:0}.fe-corner:before{inset:15%;border-top-width:1px;border-left-width:1px;border-radius:34% 0 0 0;transform:rotate(-13deg)}.fe-corner:after{width:62%;height:62%;left:-1%;top:-2%;background:radial-gradient(ellipse at 72% 72%,transparent 0 33%,#d5b5771b 34% 36%,transparent 37%),conic-gradient(from 200deg at 70% 70%,transparent 0 64%,#d5b577 65% 65.6%,transparent 66% 100%);clip-path:polygon(0 0,100% 0,0 100%)}
.fe-corner i,.fe-corner b,.fe-corner em{position:absolute;display:block;border:1px solid #d5b577;border-radius:70% 0 70% 0;transform-origin:100% 100%;opacity:.8}.fe-corner i{width:32%;height:13%;left:17%;top:16%;transform:rotate(-28deg)}.fe-corner b{width:28%;height:11%;left:6%;top:34%;transform:rotate(-55deg)}.fe-corner em{width:25%;height:10%;left:31%;top:5%;transform:rotate(-8deg)}.fe-corner.tr{right:0;top:0;transform:scaleX(-1)}.fe-corner.bl{left:0;bottom:0;transform:scaleY(-1)}.fe-corner.br{right:0;bottom:0;transform:scale(-1)}
.fe-title{position:absolute;z-index:8;top:4.4vh;left:5vw;right:5vw;text-align:center;transition:opacity .8s ease,transform 1s cubic-bezier(.16,1,.3,1);pointer-events:none}.fe-title small{display:block;font-size:clamp(7px,1.45vw,10px);letter-spacing:.4em;color:#d9bb84}.fe-title h1{margin:1.8vh 0 1vh;font:500 clamp(44px,11vw,84px)/.9 'Cormorant Garamond',serif;color:#f7e8c9;text-shadow:0 8px 28px #0005}.fe-title .rule{width:min(38vw,230px);height:1px;margin:2vh auto;background:linear-gradient(90deg,transparent,#d5b36f 20%,#f1d498 50%,#d5b36f 80%,transparent);animation:ruleBreath 4s ease-in-out infinite}.fe-title p{margin:.55vh 0;font-size:clamp(7px,1.8vw,10px);letter-spacing:.29em;text-transform:uppercase;color:#e2c792}.fe-title .fe-sub{font-size:clamp(6px,1.35vw,8px);color:#bda16d}@keyframes ruleBreath{50%{transform:scaleX(.72);opacity:.65}}
.fe-flap,.fe-left,.fe-right,.fe-bottom{position:absolute;background-image:radial-gradient(circle at 25% 24%,#e6c48c0b 0 1px,transparent 1.5px),repeating-linear-gradient(135deg,#ffffff05 0 1px,transparent 1px 9px),linear-gradient(145deg,#154474,#0a3159 60%,#061b33);box-shadow:inset 0 0 0 1px #e2bd7a10;transition:transform 1.45s cubic-bezier(.16,1,.3,1),opacity .9s ease;will-change:transform}
.fe-flap{z-index:5;left:0;right:0;top:0;height:67%;clip-path:polygon(0 0,50% 88%,100% 0);transform-origin:50% 0;filter:drop-shadow(0 26px 34px #0006)}.fe-left{z-index:3;left:0;bottom:0;width:75%;height:68%;clip-path:polygon(0 0,100% 61%,100% 100%,0 100%)}.fe-right{z-index:3;right:0;bottom:0;width:75%;height:68%;clip-path:polygon(0 61%,100% 0,100% 100%,0 100%)}.fe-bottom{z-index:4;left:0;right:0;bottom:0;height:52%;clip-path:polygon(0 100%,50% 0,100% 100%);background-image:repeating-linear-gradient(135deg,#ffffff05 0 1px,transparent 1px 9px),linear-gradient(165deg,#103960,#071f3a)}
.fe-seal{position:absolute;z-index:14;left:50%;top:60%;width:clamp(112px,18vw,164px);height:clamp(112px,18vw,164px);transform:translate(-50%,-50%);border-radius:50%;border:2px solid #f5d8a17a;display:grid;place-items:center;background:radial-gradient(circle at 34% 27%,#e8c77e,#b68842 36%,#7a5422 64%,#4b3011);box-shadow:inset 0 0 0 8px #ffedc51c,inset 0 0 0 18px #39220b2e,0 28px 55px #0009,0 0 0 1px #ffd99444;color:#f9e4bb;font:500 clamp(28px,4.5vw,42px) 'Cormorant Garamond',serif;letter-spacing:.08em;cursor:pointer;transition:opacity .55s ease,transform .75s cubic-bezier(.16,1,.3,1)}.fe-seal:before{content:"";position:absolute;inset:-17px;border:1px solid #e0be7f70;border-radius:50%;animation:sealPulse 2.4s infinite}.fe-seal:after{content:"TAP TO OPEN";position:absolute;top:calc(100% + 34px);left:50%;transform:translateX(-50%);white-space:nowrap;font:600 8px 'DM Sans';letter-spacing:.38em;color:#d9bc84}@keyframes sealPulse{50%{transform:scale(1.13);opacity:.86}0%,100%{transform:scale(.96);opacity:.34}}
.opening .fe-flap{transform:rotateX(178deg) translateZ(2px)}.opening .fe-left{transform:translateX(-17%) rotate(-1deg)}.opening .fe-right{transform:translateX(17%) rotate(1deg)}.opening .fe-bottom{transform:translateY(21%)}.opening .fe-seal{opacity:0;transform:translate(-50%,-50%) scale(.67) rotate(-8deg)}.opening .fe-title{opacity:0;transform:translateY(-28px) scale(.98)}.opening .fe-corner{opacity:0;transition:opacity .7s ease}
.fe-prologue{position:absolute;inset:0;z-index:40;background:#06111b;opacity:0;pointer-events:none;transition:opacity 1.05s ease;overflow:hidden}.prologue-on .fe-prologue{opacity:1;pointer-events:auto}.fe-photo{position:absolute;inset:-7%;background:center/cover no-repeat;opacity:0;filter:saturate(.82) brightness(.35) blur(1.5px);transform:scale(1.17) translate3d(0,0,0);transition:opacity 1.35s ease,transform 4.6s cubic-bezier(.2,.7,.2,1),filter 1.5s ease;will-change:transform,opacity}.fe-photo.show{opacity:.72;transform:scale(1.025) translate3d(var(--panx,0),var(--pany,0),0);filter:saturate(1) brightness(.55) blur(0)}.fe-photo.out{opacity:0;transform:scale(.985) translate3d(calc(var(--panx,0)*-1),calc(var(--pany,0)*-1),0);filter:saturate(.7) brightness(.32) blur(2px)}.fe-photo.alt.show{transform:scale(1.04) translate3d(var(--panx,0),var(--pany,0),0) rotate(.35deg)}
.fe-vignette{position:absolute;inset:0;z-index:3;background:linear-gradient(180deg,#02070d52 0,#02070d08 24%,#02070d10 68%,#02070d8f 100%),radial-gradient(circle at 50% 45%,transparent 0 24%,#03090f3d 58%,#03090fdc 100%);pointer-events:none}.fe-grain{position:absolute;inset:-100%;z-index:4;opacity:.055;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='.7'/%3E%3C/svg%3E");animation:grain .32s steps(2) infinite;pointer-events:none}@keyframes grain{0%{transform:translate(0,0)}25%{transform:translate(2%,-1%)}50%{transform:translate(-1%,2%)}75%{transform:translate(1%,1%)}100%{transform:translate(-2%,-1%)}}
.fe-story{position:absolute;inset:0;z-index:9;display:grid;place-items:center;text-align:center;padding:7vh 7vw}.fe-scene{position:absolute;left:5.5vw;right:5.5vw;top:50%;opacity:0;transform:translate3d(0,32px,0) scale(.94);filter:blur(5px);transition:opacity .8s ease,transform 1.15s cubic-bezier(.16,1,.3,1),filter .8s ease;text-shadow:0 8px 36px #000c;pointer-events:none}.fe-scene.show{opacity:1;transform:translate3d(0,-50%,0) scale(1);filter:blur(0)}.fe-scene.hide{opacity:0;transform:translate3d(0,-61%,0) scale(1.045);filter:blur(4px)}.fe-scene h2{margin:0;color:#fff7e8;font:500 clamp(42px,10vw,90px)/.94 'Cormorant Garamond',serif;letter-spacing:-.025em}.fe-scene p{max-width:740px;margin:22px auto 0;color:#e3c68e;font:500 clamp(9px,2vw,13px)/1.6 'DM Sans';letter-spacing:.15em;text-transform:uppercase}.fe-scene h2 .w{display:inline-block;opacity:0;transform:translateY(22px) rotateX(32deg);filter:blur(6px)}.fe-scene.show h2 .w{animation:wordRise .72s cubic-bezier(.16,1,.3,1) forwards;animation-delay:calc(var(--i)*80ms)}@keyframes wordRise{to{opacity:1;transform:none;filter:blur(0)}}.fe-scene.show p{animation:subReveal .9s .4s both cubic-bezier(.16,1,.3,1)}@keyframes subReveal{from{opacity:0;transform:translateY(12px);letter-spacing:.28em}to{opacity:1;transform:none}}
.fe-scene.kind-question h2{font-style:italic}.fe-scene.kind-question:before{content:"";display:block;width:1px;height:74px;margin:0 auto 24px;background:linear-gradient(transparent,#d7b477)}.fe-scene.kind-split.show h2{animation:gentleFloat 3s ease-in-out infinite}.fe-scene.kind-words.show h2 .w:nth-child(even){animation-name:wordDrop}.fe-scene.kind-sweep:after{content:"";display:block;height:1px;width:0;margin:25px auto 0;background:linear-gradient(90deg,transparent,#e0be7f,transparent)}.fe-scene.kind-sweep.show:after{animation:sweepLine 2.2s .35s both ease}@keyframes sweepLine{to{width:min(70vw,510px)}}@keyframes wordDrop{from{opacity:0;transform:translateY(-20px);filter:blur(5px)}to{opacity:1;transform:none;filter:blur(0)}}@keyframes gentleFloat{50%{transform:translateY(-5px)}}
.fe-scene.kind-hero h2,.fe-scene.kind-date h2{font-size:clamp(58px,13vw,118px);color:#f5dfb7}.fe-scene.kind-hero.show{animation:heroGlow 3s ease-in-out both}@keyframes heroGlow{45%{text-shadow:0 0 50px #e4bf7c55,0 9px 36px #000}}
.fe-scene.kind-fun h2:after,.fe-scene.kind-pop h2:after{content:" ✦";font-size:.32em;color:#d5ac72}.fe-scene.kind-fun.show{animation:funTilt 3.1s ease-in-out both}.fe-scene.kind-tilt.show{transform:translate3d(0,-50%,0) rotate(-1.1deg)}.fe-scene.kind-pop.show h2{animation:tinyPop .8s .1s both cubic-bezier(.16,1,.3,1)}@keyframes funTilt{40%{transform:translate3d(0,-51%,0) rotate(.6deg)}70%{transform:translate3d(0,-49.5%,0) rotate(-.3deg)}}@keyframes tinyPop{0%{transform:scale(.8)}70%{transform:scale(1.035)}100%{transform:scale(1)}}
.fe-scene.kind-script h2{font-style:italic}.fe-scene.kind-church:before{content:"✝";display:block;margin-bottom:18px;font:400 30px serif;color:#d7b477;opacity:0;transform:translateY(-12px)}.fe-scene.kind-church.show:before{animation:subReveal .8s .2s both}.fe-scene.kind-party:before{content:"✦   ✦   ✦";display:block;margin-bottom:18px;color:#d7b477;letter-spacing:.48em;animation:sparkText 1.6s infinite alternate ease-in-out}@keyframes sparkText{to{letter-spacing:.68em;opacity:.65}}.fe-scene.kind-cake:before{content:"♡";display:block;margin-bottom:15px;color:#d7b477;font:400 34px serif}
.fe-program{width:min(92vw,760px);margin:auto;padding:clamp(25px,5vw,52px);border:1px solid #d4b47870;background:linear-gradient(145deg,#071521da,#06111bcf);backdrop-filter:blur(14px);box-shadow:0 34px 90px #0008;position:relative;overflow:hidden}.fe-program:before{content:"";position:absolute;inset:-120% -20%;background:linear-gradient(110deg,transparent 44%,#f5dcae16 50%,transparent 56%);transform:translateX(-28%);animation:programmeShine 3.2s ease-in-out infinite}@keyframes programmeShine{to{transform:translateX(28%)}}.fe-program .pk{font:600 8px 'DM Sans';letter-spacing:.38em;color:#d4b478;text-transform:uppercase;position:relative}.fe-program h2{font-size:clamp(45px,9vw,78px);margin:12px 0 22px;position:relative}.fe-program-grid{border-top:1px solid #d4b47866;position:relative}.fe-program-row{display:grid;grid-template-columns:minmax(92px,1fr) 2.4fr;gap:18px;padding:15px 0;border-bottom:1px solid #d4b4783d;text-align:left;opacity:0;transform:translateX(-20px)}.fe-scene.show .fe-program-row{animation:rowIn .6s cubic-bezier(.16,1,.3,1) forwards;animation-delay:calc(var(--r)*120ms + .35s)}@keyframes rowIn{to{opacity:1;transform:none}}.fe-program-row b{font:500 clamp(21px,4vw,34px) 'Cormorant Garamond';color:#f5dfb7}.fe-program-row span{align-self:center;font-size:clamp(8px,1.7vw,12px);letter-spacing:.1em;color:#fff9;line-height:1.5}
.fe-rose{position:absolute;z-index:8;opacity:0;color:#e1b7b1;filter:drop-shadow(0 6px 10px #0005);font-size:clamp(24px,7vw,62px);transform:scale(.05) rotate(var(--r));transition:1.15s cubic-bezier(.16,1,.3,1);pointer-events:none}.fe-rose:before{content:"✿"}.fe-rose.bloom{opacity:.88;transform:scale(1) rotate(var(--r))}.fe-rose.fade{opacity:0;transform:scale(1.35) rotate(calc(var(--r) + 20deg))}.fe-petal{position:absolute;z-index:8;top:-5vh;color:#e9c7c1;font-size:16px;animation:petalFall var(--d) linear forwards;pointer-events:none}@keyframes petalFall{0%{opacity:0;transform:translateY(-5vh) rotate(0)}10%{opacity:.8}100%{opacity:0;transform:translate3d(var(--x),110vh,0) rotate(420deg)}}
.fe-progress{position:absolute;z-index:15;left:7vw;right:7vw;bottom:3.6vh;height:1px;background:#ffffff20;overflow:hidden}.fe-progress i{display:block;height:100%;width:0;background:linear-gradient(90deg,#9c7746,#f3dcae,#d1aa73);box-shadow:0 0 8px #d1aa7377;transition:width .8s cubic-bezier(.16,1,.3,1)}.fe-counter{position:absolute;z-index:15;right:7vw;bottom:4.8vh;font:500 7px 'DM Sans';letter-spacing:.25em;color:#fff8}.fe-skip{position:absolute;z-index:16;left:7vw;bottom:4.5vh;border:0;background:transparent;color:#ffffff67;font:600 7px 'DM Sans';letter-spacing:.24em;text-transform:uppercase;padding:10px 0}.leaving{opacity:0!important;transform:scale(1.02);transition:opacity 1.05s ease,transform 1.2s ease;pointer-events:none!important}
@media(max-width:500px){.fe-title{top:3.6vh}.fe-title h1{font-size:43px}.fe-title p{font-size:7px}.fe-seal{top:61%;width:112px;height:112px;font-size:29px}.fe-scene{left:5vw;right:5vw}.fe-scene h2{font-size:43px}.fe-scene.kind-hero h2,.fe-scene.kind-date h2{font-size:64px}.fe-program{padding:22px 18px}.fe-program-row{grid-template-columns:90px 1fr;gap:10px;padding:11px 0}.fe-program-row b{font-size:24px}.fe-corner{width:120px;height:120px}.fe-progress{bottom:3.2vh}.fe-counter{bottom:4.3vh}.fe-skip{bottom:4vh}}
@media(prefers-reduced-motion:reduce){.fe-photo,.fe-scene,.fe-flap,.fe-left,.fe-right,.fe-bottom{transition-duration:.25s!important}.fe-rose,.fe-petal,.fe-grain{display:none!important}.fe-scene h2 .w{opacity:1!important;transform:none!important;filter:none!important;animation:none!important}}
`;document.head.appendChild(s)}
function wrapWords(el){if(!el||el.dataset.words)return;const text=el.textContent.trim();el.textContent='';text.split(/\s+/).forEach((w,i)=>{const span=document.createElement('span');span.className='w';span.style.setProperty('--i',i);span.textContent=w+' ';el.appendChild(span)});el.dataset.words='1'}
function bloom(layer){for(let i=0;i<22;i++){const r=document.createElement('span');r.className='fe-rose';r.style.left=(Math.random()*98-3)+'vw';r.style.top=(3+Math.random()*90)+'vh';r.style.setProperty('--r',(Math.random()*80-40)+'deg');layer.appendChild(r);setTimeout(()=>r.classList.add('bloom'),i*45);setTimeout(()=>r.classList.add('fade'),2350+i*12);setTimeout(()=>r.remove(),3600)}for(let i=0;i<24;i++){const p=document.createElement('span');p.className='fe-petal';p.textContent='•';p.style.left=Math.random()*100+'vw';p.style.setProperty('--x',(Math.random()*160-80)+'px');p.style.setProperty('--d',(3.2+Math.random()*2.4)+'s');p.style.animationDelay=Math.random()*.75+'s';layer.appendChild(p);setTimeout(()=>p.remove(),6200)}}
function installLanding(){if(q('#fullEnvelopeLanding'))return;addStyles();const l=document.createElement('div');l.id='fullEnvelopeLanding';l.innerHTML=`<div class="fe-corner tl"><i></i><b></b><em></em></div><div class="fe-corner tr"><i></i><b></b><em></em></div><div class="fe-corner bl"><i></i><b></b><em></em></div><div class="fe-corner br"><i></i><b></b><em></em></div><div class="fe-title"><small>A PRIVATE INVITATION</small><h1>Dr Martin &amp; Pearl</h1><div class="rule"></div><p>Some things are simply meant to be</p><p class="fe-sub">Love · Faith · A Beautiful Future</p></div><div class="fe-flap"></div><div class="fe-left"></div><div class="fe-right"></div><div class="fe-bottom"></div><button class="fe-seal" aria-label="Open invitation">M&amp;P</button><div class="fe-prologue"><div class="fe-photos"></div><div class="fe-vignette"></div><div class="fe-grain"></div><div class="fe-story"></div><div class="fe-roses"></div><button class="fe-skip" type="button">Skip intro</button><div class="fe-progress"><i></i></div><div class="fe-counter"></div></div>`;document.body.appendChild(l);
const photos=q('.fe-photos',l),story=q('.fe-story',l),roses=q('.fe-roses',l),counter=q('.fe-counter',l),prog=q('.fe-progress i',l),skip=q('.fe-skip',l);
DRIVE_IDS.forEach((id,i)=>{const d=document.createElement('div');d.className='fe-photo'+(i%2?' alt':'');d.style.backgroundImage=`url("${drive(id)}")`;d.style.setProperty('--panx',((i%3)-1)*2.1+'%');d.style.setProperty('--pany',((i%2)?-1.5:1.3)+'%');photos.appendChild(d)});
scenes.forEach((sc,i)=>{const d=document.createElement('section');d.className=`fe-scene kind-${sc.kind||'base'}`;if(sc.program){d.innerHTML=`<div class="fe-program"><div class="pk">Dr Martin & Pearl · 22 December 2026</div><h2>Wedding Programme</h2><div class="fe-program-grid"><div class="fe-program-row" style="--r:0"><b>10:00 AM</b><span>Holy Matrimony · St. Mary’s Cathedral Rubaga<br>His Grace Archbishop Paul Ssemogerere</span></div><div class="fe-program-row" style="--r:1"><b>2:30 PM</b><span>Reception · Mutima Hall</span></div><div class="fe-program-row" style="--r:2"><b>4:00 PM</b><span>Dinner</span></div><div class="fe-program-row" style="--r:3"><b>6:00 PM</b><span>Cake</span></div><div class="fe-program-row" style="--r:4"><b>After</b><span>Music · Family · Celebration</span></div></div></div>`}else{d.innerHTML=`<h2>${sc.big}</h2><p>${sc.small}</p>`;wrapWords(q('h2',d))}story.appendChild(d)});
const photoEls=qa('.fe-photo',l),sceneEls=qa('.fe-scene',l);let timers=[],finished=false;
const later=(fn,ms)=>{const t=setTimeout(fn,ms);timers.push(t);return t};
function finish(){if(finished)return;finished=true;timers.forEach(clearTimeout);sceneEls.forEach(x=>x.classList.remove('show'));l.classList.add('leaving');later(()=>{l.remove();document.documentElement.style.overflow='';document.body.style.overflow='';const first=q('#storybook,.storybook,.chapter');if(first)first.scrollIntoView({behavior:'smooth',block:'start'})},950)}
function showScene(i){sceneEls.forEach((e,j)=>{e.classList.toggle('show',j===i);e.classList.toggle('hide',j<i)});photoEls.forEach((e,j)=>{const idx=i%photoEls.length;e.classList.toggle('show',j===idx);e.classList.toggle('out',j!==idx&&e.classList.contains('show'))});counter.textContent=`${String(i+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;prog.style.width=((i+1)/scenes.length*100)+'%';if(scenes[i]?.rose)bloom(roses)}
function run(){document.documentElement.style.overflow='hidden';document.body.style.overflow='hidden';l.classList.add('opening');const underlying=q('.intro .seal');if(underlying)underlying.click();later(()=>l.classList.add('prologue-on'),850);scenes.forEach((_,i)=>later(()=>showScene(i),1350+i*HOLD));later(finish,1350+scenes.length*HOLD+700)}
q('.fe-seal',l).addEventListener('click',run,{once:true});skip.addEventListener('click',finish);}
function installStorybook(){const pages=qa('.chapter').slice(0,5);if(!pages.length||q('#storybook'))return;const book=document.createElement('div');book.className='storybook';book.id='storybook';pages[0].parentNode.insertBefore(book,pages[0]);pages.forEach((page,i)=>{page.classList.add('book-page');page.dataset.page=i;const edge=document.createElement('div');edge.className='page-edge';const num=document.createElement('div');num.className='page-number';num.textContent=`0${i+1} / 05`;page.append(edge,num);book.appendChild(page)});let raf=0;const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));function turn(){raf=0;const top=book.offsetTop,vh=innerHeight;pages.forEach((page,i)=>{const p=clamp((scrollY-(top+i*vh))/vh,0,1),e=1-Math.pow(1-p,2.55);page.style.zIndex=60-i;page.style.transform=`translate3d(0,${-Math.sin(p*Math.PI)*16}px,0) rotateY(${-178*e}deg) scale(${1-Math.sin(p*Math.PI)*.018})`;page.style.filter=`brightness(${1-p*.17})`;page.classList.toggle('turning',p>.04&&p<.96)});}const schedule=()=>{if(!raf)raf=requestAnimationFrame(turn)};addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);turn()}
function boot(){installLanding();installStorybook()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();