(()=>{
'use strict';
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
const IDS=['1RVfbarYJg3p7SZjeiFIHq2PrY2V26aLH','1o3ESuqFtG9MM2-4tPu5BINiB1AH_OTSI','1Yc5KV4QLBDPW7_AbMsua2c639_j2a64q','1ZCCpWXnBzGxrwkQTqdA0ULmw07rg3qXr','1trAhd8ztTuWpWIX0m2QEmdLlLFIb7BCN','1YBf3V8S_7WwXl4PZa-Ay16xg8kQEbgpt','1veT3F-5LedP7EmvdnxichO11pFQR27EI','1gBpU-xcqlgaRQPaFfLRlqxqbSEGYYpgL','1ZRnAXHUMuEfF8nIigfRlCYfa797lESRw','1LJDUZ9lgGPVqPlamYxEjcjZ5wIZhKSK2','1y7GBwCcsG-j-tO4QE6kLDyKuCNRCJEQE','1fIM4VjAf2rD_XacwO5Z1zZOwFFgdTeRi','1lgd7mSvXL-KNj8EnmoDYT66VqStcUMBP','1PUOQWqoA-9o_W1gdJNcT0URqXJTX6btP'];
const img=id=>`https://drive.google.com/thumbnail?id=${id}&sz=w1800`;
const HOLD=4600;
const scenes=[
 ['What is love?','Perhaps it begins quietly.','full'],
 ['A glance that stays.','A hand that begins to feel like home.','split'],
 ['Two lives choosing one another.','Again. And again.','print'],
 ['Until forever stops sounding far away.','And starts sounding like us.','mask'],
 ['You are invited.','22 · 12 · 2026','hero'],
 ['Now… about these two.','They met. Nobody announced, “this is forever.”','split'],
 ['It was probably meant to be casual.','Then one conversation somehow needed another.','print'],
 ['Then another.','And suddenly “see you sometime” became “when are we meeting?”','mask'],
 ['The funny thing about forever…','It rarely introduces itself properly.','full'],
 ['It just keeps showing up.','In laughter. In patience. In choosing each other.','print'],
 ['So they chose a date.','Tuesday · 22 December 2026','hero'],
 ['First, the promise.','10:00 AM · St. Mary’s Cathedral Rubaga','mask'],
 ['With a special blessing.','Holy Matrimony by His Grace Archbishop Paul Ssemogerere','split'],
 ['Then… we celebrate.','2:30 PM · Reception · Mutima Hall','full'],
 ['Come hungry.','4:00 PM · Dinner','print'],
 ['And save room.','6:00 PM · Cake','mask'],
 ['Bring your best smile.','The rest of the evening belongs to music, family & joy.','split'],
 ['PROGRAM','','program']
];
function addCSS(){if(q('#vintageJourneyStyle'))return;const s=document.createElement('style');s.id='vintageJourneyStyle';s.textContent=`
#snowField{position:fixed;inset:0;z-index:1200;pointer-events:none;overflow:hidden}.snowflake{position:absolute;top:-8vh;width:var(--sz);height:var(--sz);border-radius:50%;background:rgba(255,255,255,.86);box-shadow:0 0 10px rgba(255,255,255,.35);opacity:.72;animation:snowFall var(--dur) linear infinite;animation-delay:var(--delay)}@keyframes snowFall{0%{transform:translate3d(0,-8vh,0)}50%{transform:translate3d(var(--drift),54vh,0)}100%{transform:translate3d(calc(var(--drift)*-.35),112vh,0)}}
#fullEnvelopeLanding{position:fixed;inset:0;z-index:1000;width:100vw;height:100dvh;min-height:100svh;overflow:hidden;background:#082746;color:#f5dfb7;font-family:'DM Sans',sans-serif;perspective:1800px;isolation:isolate}#fullEnvelopeLanding:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 36%,rgba(55,112,164,.22),transparent 45%),repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 1px,transparent 1px 10px)}
.fe-corner{position:absolute;z-index:11;width:150px;height:150px;opacity:.55;pointer-events:none}.fe-corner:before{content:"❧";position:absolute;font:400 94px/1 'Cormorant Garamond',serif;color:#c9a76d;text-shadow:0 0 18px #c9a76d22}.fe-corner.tl{left:-5px;top:-7px}.fe-corner.tr{right:-5px;top:-7px;transform:scaleX(-1)}.fe-corner.bl{left:-5px;bottom:-7px;transform:scaleY(-1)}.fe-corner.br{right:-5px;bottom:-7px;transform:scale(-1)}
.fe-title{position:absolute;z-index:8;top:4.6vh;left:5vw;right:5vw;text-align:center;transition:opacity 1s ease,transform 1.2s cubic-bezier(.2,.75,.22,1)}.fe-title small{display:block;font-size:9px;letter-spacing:.38em;color:#d6b77e}.fe-title h1{margin:1.8vh 0 1.1vh;font:500 clamp(44px,11vw,84px)/.9 'Cormorant Garamond',serif;color:#f7e8ca}.fe-title .rule{width:min(38vw,230px);height:1px;margin:2vh auto;background:linear-gradient(90deg,transparent,#d6b577,transparent)}.fe-title p{margin:.5vh 0;font-size:clamp(7px,1.8vw,10px);letter-spacing:.27em;text-transform:uppercase;color:#dfc28d}
.fe-flap,.fe-left,.fe-right,.fe-bottom{position:absolute;background-image:repeating-linear-gradient(135deg,#ffffff04 0 1px,transparent 1px 10px),linear-gradient(145deg,#154474,#0b335d 60%,#071d36);transition:transform 2s cubic-bezier(.2,.72,.22,1),opacity 1.05s ease;will-change:transform}.fe-flap{z-index:5;inset:0 0 auto;height:67%;clip-path:polygon(0 0,50% 88%,100% 0);transform-origin:50% 0;filter:drop-shadow(0 22px 30px #0006)}.fe-left{z-index:3;left:0;bottom:0;width:75%;height:68%;clip-path:polygon(0 0,100% 61%,100% 100%,0 100%)}.fe-right{z-index:3;right:0;bottom:0;width:75%;height:68%;clip-path:polygon(0 61%,100% 0,100% 100%,0 100%)}.fe-bottom{z-index:4;left:0;right:0;bottom:0;height:52%;clip-path:polygon(0 100%,50% 0,100% 100%);background-image:repeating-linear-gradient(135deg,#ffffff04 0 1px,transparent 1px 10px),linear-gradient(165deg,#103960,#071f3a)}
.fe-seal{position:absolute;z-index:14;left:50%;top:60%;width:clamp(112px,18vw,164px);height:clamp(112px,18vw,164px);transform:translate(-50%,-50%);border-radius:50%;border:2px solid #f5d8a17a;display:grid;place-items:center;background:radial-gradient(circle at 34% 27%,#e8c77e,#b68842 36%,#7a5422 64%,#4b3011);box-shadow:inset 0 0 0 8px #ffedc51c,inset 0 0 0 18px #39220b2e,0 28px 55px #0009;color:#f9e4bb;font:500 clamp(28px,4.5vw,42px) 'Cormorant Garamond',serif;letter-spacing:.08em;cursor:pointer;transition:opacity .8s ease,transform 1s ease}.fe-seal:before{content:"";position:absolute;inset:-17px;border:1px solid #e0be7f70;border-radius:50%;animation:sealPulse 2.8s ease-in-out infinite}.fe-seal:after{content:"TAP TO OPEN";position:absolute;top:calc(100% + 34px);left:50%;transform:translateX(-50%);white-space:nowrap;font:600 8px 'DM Sans';letter-spacing:.38em;color:#d9bc84}@keyframes sealPulse{50%{transform:scale(1.08);opacity:.7}0%,100%{transform:scale(.98);opacity:.38}}
.opening .fe-flap{transform:rotateX(178deg)}.opening .fe-left{transform:translateX(-14%)}.opening .fe-right{transform:translateX(14%)}.opening .fe-bottom{transform:translateY(17%)}.opening .fe-seal{opacity:0;transform:translate(-50%,-50%) scale(.72)}.opening .fe-title,.opening .fe-corner{opacity:0}.opening .fe-title{transform:translateY(-18px)}
.fe-prologue{position:absolute;inset:0;z-index:40;background:#090d12;opacity:0;pointer-events:none;transition:opacity 1.45s ease;overflow:hidden}.prologue-on .fe-prologue{opacity:1;pointer-events:auto}.fe-vignette{position:absolute;inset:0;z-index:6;background:linear-gradient(180deg,#09080a40,transparent 26%,transparent 65%,#08080ad0),radial-gradient(circle at 50% 45%,transparent 0 28%,#17100c30 62%,#060708d8 100%);pointer-events:none}.fe-grain{position:absolute;inset:-30%;z-index:7;opacity:.075;background-image:radial-gradient(circle,#fff 0 .5px,transparent .8px);background-size:4px 4px;mix-blend-mode:soft-light;animation:grainShift .5s steps(2) infinite;pointer-events:none}@keyframes grainShift{50%{transform:translate3d(1.5%,-1%,0)}}
.photo-stage{position:absolute;inset:0;z-index:2;overflow:hidden}.shot{position:absolute;opacity:0;filter:sepia(.24) saturate(.72) contrast(1.06) brightness(.72);box-shadow:0 35px 90px #0009;will-change:transform,opacity,clip-path}.shot.show{opacity:1}.shot.full{inset:-5%;background:center/cover no-repeat;transform:scale(1.1);transition:opacity 1.55s ease,transform 7s cubic-bezier(.22,.64,.28,1),filter 1.5s ease}.shot.full.show{transform:scale(1.015);filter:sepia(.22) saturate(.78) contrast(1.08) brightness(.82)}.shot.mask{left:8vw;right:8vw;top:10vh;bottom:10vh;background:center/cover no-repeat;clip-path:inset(48% 12% 48% 12% round 28px);transform:scale(1.06);transition:opacity 1.2s ease,clip-path 2.1s cubic-bezier(.16,1,.3,1),transform 6.5s ease}.shot.mask.show{clip-path:inset(0 0 0 0 round 28px);transform:scale(1.01)}.shot.split{top:9vh;bottom:9vh;width:44vw;background:center/cover no-repeat;transition:opacity 1.35s ease,transform 2.2s cubic-bezier(.16,1,.3,1)}.shot.split.a{left:3vw;transform:translateX(-14vw) rotate(-2deg)}.shot.split.b{right:3vw;transform:translateX(14vw) rotate(2deg)}.shot.split.show.a,.shot.split.show.b{transform:translateX(0) rotate(0)}.shot.print{width:min(72vw,560px);height:min(61vh,660px);left:50%;top:50%;background:center/cover no-repeat;border:12px solid #eee4d5;border-bottom-width:42px;transform:translate(-50%,-47%) rotate(var(--rot)) scale(.86);transition:opacity 1.2s ease,transform 2.2s cubic-bezier(.16,1,.3,1)}.shot.print.show{transform:translate(-50%,-50%) rotate(var(--rot)) scale(1)}.shot.print.back{filter:sepia(.35) saturate(.58) contrast(1.03) brightness(.68);opacity:0}.shot.print.back.show{opacity:.55;transform:translate(-57%,-53%) rotate(calc(var(--rot) - 5deg)) scale(.96)}
.fe-story{position:absolute;inset:0;z-index:10;display:grid;place-items:center;text-align:center;padding:7vh 7vw}.fe-scene{position:absolute;left:6vw;right:6vw;top:50%;opacity:0;transform:translate3d(0,-45%,0);transition:opacity 1.3s ease,transform 1.7s cubic-bezier(.22,.75,.25,1);text-shadow:0 8px 32px #000c;pointer-events:none}.fe-scene.show{opacity:1;transform:translate3d(0,-50%,0)}.fe-scene.hide{opacity:0;transform:translate3d(0,-55%,0)}.fe-scene h2{margin:0;color:#fff8ea;font:500 clamp(42px,9.5vw,88px)/.98 'Cormorant Garamond',serif;letter-spacing:-.018em}.fe-scene p{max-width:760px;margin:22px auto 0;color:#e5c994;font:500 clamp(9px,1.9vw,13px)/1.65 'DM Sans';letter-spacing:.13em;text-transform:uppercase}.fe-scene.hero h2{font-size:clamp(58px,13vw,116px);color:#f5dfb7}.fe-scene.show h2{animation:textEase 1.35s cubic-bezier(.22,.75,.25,1) both}.fe-scene.show p{animation:subEase 1.4s .22s cubic-bezier(.22,.75,.25,1) both}@keyframes textEase{from{opacity:0;transform:translateY(20px);filter:blur(4px)}to{opacity:1;transform:none;filter:blur(0)}}@keyframes subEase{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}
.fe-rose{position:absolute;z-index:8;font-size:clamp(24px,6vw,54px);color:#dfb3ae;opacity:0;transform:scale(.2);transition:opacity 1.25s ease,transform 1.8s cubic-bezier(.22,.75,.25,1);pointer-events:none}.fe-rose:before{content:"✿"}.fe-rose.bloom{opacity:.7;transform:scale(1)}.fe-petal{position:absolute;z-index:8;top:-4vh;color:#e9c7c1;font-size:13px;animation:petalFall var(--d) linear forwards}@keyframes petalFall{0%{opacity:0;transform:translateY(-4vh) rotate(0)}15%{opacity:.58}100%{opacity:0;transform:translate3d(var(--x),108vh,0) rotate(300deg)}}
.fe-program{width:min(90vw,720px);padding:clamp(26px,5vw,50px);border:1px solid #d4b47866;background:#0a1014d8;backdrop-filter:blur(12px);box-shadow:0 30px 80px #0008}.fe-program .pk{font:600 8px 'DM Sans';letter-spacing:.38em;color:#d4b478;text-transform:uppercase}.fe-program h2{font-size:clamp(44px,9vw,76px);margin:12px 0 22px}.fe-program-row{display:grid;grid-template-columns:105px 1fr;gap:16px;padding:14px 0;border-top:1px solid #d4b4783d;text-align:left;opacity:0;transform:translateY(12px)}.fe-scene.show .fe-program-row{animation:rowIn .8s ease forwards;animation-delay:calc(var(--i)*180ms + 420ms)}@keyframes rowIn{to{opacity:1;transform:none}}.fe-program-row b{font:500 clamp(21px,4vw,32px) 'Cormorant Garamond';color:#f5dfb7}.fe-program-row span{align-self:center;font-size:clamp(8px,1.7vw,12px);letter-spacing:.09em;color:#fff9;line-height:1.5}
.fe-progress{position:absolute;z-index:13;left:7vw;right:7vw;bottom:3.8vh;height:1px;background:#fff2}.fe-progress i{display:block;height:100%;width:0;background:linear-gradient(90deg,#d1aa73,#f3dcae);transition:width 1.2s ease}.leaving{opacity:0!important;transform:scale(1.012);transition:opacity 1.4s ease,transform 1.6s ease;pointer-events:none!important}
@media(max-width:600px){.fe-title{top:3.7vh}.fe-title h1{font-size:43px}.fe-title p{font-size:7px}.fe-seal{top:61%;width:112px;height:112px;font-size:29px}.fe-corner{width:112px;height:112px}.fe-corner:before{font-size:72px}.fe-scene{left:5vw;right:5vw}.fe-scene h2{font-size:42px}.fe-scene.hero h2{font-size:62px}.shot.split{width:46vw;top:12vh;bottom:12vh}.shot.print{width:78vw;height:58vh}.shot.mask{left:5vw;right:5vw;top:12vh;bottom:12vh}.fe-program{padding:24px 18px}.fe-program-row{grid-template-columns:88px 1fr;gap:10px}.fe-program-row b{font-size:24px}}
@media(prefers-reduced-motion:reduce){.shot,.fe-scene,.fe-flap,.fe-left,.fe-right,.fe-bottom{transition-duration:.25s!important}.snowflake,.fe-rose,.fe-petal{display:none!important}}
`;document.head.appendChild(s)}
function snow(){if(q('#snowField'))return;const f=document.createElement('div');f.id='snowField';for(let i=0;i<26;i++){const n=document.createElement('i');n.className='snowflake';n.style.left=Math.random()*100+'vw';n.style.setProperty('--sz',(2+Math.random()*3.5)+'px');n.style.setProperty('--dur',(8+Math.random()*9)+'s');n.style.setProperty('--delay',(-Math.random()*12)+'s');n.style.setProperty('--drift',(Math.random()*90-45)+'px');f.appendChild(n)}document.body.appendChild(f)}
function petals(layer){for(let i=0;i<10;i++){const r=document.createElement('span');r.className='fe-rose';r.style.left=(4+Math.random()*90)+'vw';r.style.top=(8+Math.random()*80)+'vh';layer.appendChild(r);setTimeout(()=>r.classList.add('bloom'),i*100);setTimeout(()=>r.remove(),5600)}for(let i=0;i<12;i++){const p=document.createElement('span');p.className='fe-petal';p.textContent='•';p.style.left=Math.random()*100+'vw';p.style.setProperty('--x',(Math.random()*90-45)+'px');p.style.setProperty('--d',(5.5+Math.random()*2.5)+'s');p.style.animationDelay=Math.random()*.7+'s';layer.appendChild(p);setTimeout(()=>p.remove(),8500)}}
function install(){if(q('#fullEnvelopeLanding'))return;addCSS();snow();const l=document.createElement('div');l.id='fullEnvelopeLanding';l.innerHTML=`<div class="fe-corner tl"></div><div class="fe-corner tr"></div><div class="fe-corner bl"></div><div class="fe-corner br"></div><div class="fe-title"><small>A PRIVATE INVITATION</small><h1>Dr Martin &amp; Pearl</h1><div class="rule"></div><p>Some things are simply meant to be</p><p>Love · Faith · A Beautiful Future</p></div><div class="fe-flap"></div><div class="fe-left"></div><div class="fe-right"></div><div class="fe-bottom"></div><button class="fe-seal" aria-label="Open invitation">M&amp;P</button><div class="fe-prologue"><div class="photo-stage"></div><div class="fe-vignette"></div><div class="fe-grain"></div><div class="fe-story"></div><div class="fe-roses"></div><div class="fe-progress"><i></i></div></div>`;document.body.appendChild(l);
 const stage=q('.photo-stage',l),story=q('.fe-story',l),rose=q('.fe-roses',l),bar=q('.fe-progress i',l);scenes.forEach((sc,i)=>{const d=document.createElement('section');d.className='fe-scene '+(sc[2]==='hero'?'hero':'');if(sc[2]==='program')d.innerHTML=`<div class="fe-program"><div class="pk">THE WEDDING DAY</div><h2>Programme</h2>${[['10:00 AM','Church ceremony · St. Mary’s Cathedral Rubaga'],['2:30 PM','Reception · Mutima Hall'],['4:00 PM','Dinner'],['6:00 PM','Cake'],['Evening','Music, family & celebration']].map((x,j)=>`<div class="fe-program-row" style="--i:${j}"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')}</div>`;else d.innerHTML=`<h2>${sc[0]}</h2><p>${sc[1]}</p>`;story.appendChild(d)});
 const sceneEls=qa('.fe-scene',l);let currentShots=[];
 function clearShots(){currentShots.forEach(x=>{x.style.opacity='0';x.style.transform+=' scale(.985)';setTimeout(()=>x.remove(),1500)});currentShots=[]}
 function makeShot(cls,id,extra=''){const d=document.createElement('div');d.className='shot '+cls+' '+extra;d.style.backgroundImage=`url("${img(id)}")`;stage.appendChild(d);currentShots.push(d);requestAnimationFrame(()=>requestAnimationFrame(()=>d.classList.add('show')));return d}
 function showVisual(i,type){clearShots();const a=IDS[i%IDS.length],b=IDS[(i+4)%IDS.length];if(type==='split'){makeShot('split',a,'a');setTimeout(()=>makeShot('split',b,'b'),180)}else if(type==='print'){const back=makeShot('print',b,'back');back.style.setProperty('--rot','-4deg');const front=makeShot('print',a);front.style.setProperty('--rot','2deg')}else if(type==='mask'){makeShot('mask',a)}else{makeShot('full',a)}}
 function finish(){l.classList.add('leaving');setTimeout(()=>{l.remove();document.body.classList.add('opened');const intro=q('.intro');if(intro)intro.style.display='none';scrollTo({top:0,behavior:'smooth'})},1500)}
 let idx=0,timer;function play(i){if(i>=scenes.length){finish();return}idx=i;sceneEls.forEach((e,j)=>{e.classList.toggle('show',j===i);e.classList.toggle('hide',j<i)});const type=scenes[i][2];showVisual(i,type==='program'?'full':type);bar.style.width=((i+1)/scenes.length*100)+'%';if(i===0||i===3||i===8)petals(rose);timer=setTimeout(()=>play(i+1),HOLD)}
 q('.fe-seal',l).addEventListener('click',()=>{l.classList.add('opening');const old=q('.intro .seal');if(old)try{old.click()}catch(e){}setTimeout(()=>{l.classList.add('prologue-on');play(0)},1450)},{once:true});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();