(()=>{
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const DRIVE_IDS=['1RVfbarYJg3p7SZjeiFIHq2PrY2V26aLH','1o3ESuqFtG9MM2-4tPu5BINiB1AH_OTSI','1Yc5KV4QLBDPW7_AbMsua2c639_j2a64q','1ZCCpWXnBzGxrwkQTqdA0ULmw07rg3qXr','1trAhd8ztTuWpWIX0m2QEmdLlLFIb7BCN','1YBf3V8S_7WwXl4PZa-Ay16xg8kQEbgpt','1veT3F-5LedP7EmvdnxichO11pFQR27EI','1gBpU-xcqlgaRQPaFfLRlqxqbSEGYYpgL','1ZRnAXHUMuEfF8nIigfRlCYfa797lESRw','1LJDUZ9lgGPVqPlamYxEjcjZ5wIZhKSK2','1y7GBwCcsG-j-tO4QE6kLDyKuCNRCJEQE','1fIM4VjAf2rD_XacwO5Z1zZOwFFgdTeRi'];
const drive=id=>`https://drive.google.com/thumbnail?id=${id}&sz=w1800`;
const scenes=[
 {big:'What is love?',small:'Perhaps it begins quietly.',rose:1},
 {big:'A glance that stays.',small:'A hand that begins to feel like home.'},
 {big:'Two lives choosing one another.',small:'Again. And again.'},
 {big:'Until forever stops sounding far away.',small:'And starts sounding like us.',rose:1},
 {big:'You are invited.',small:'22 · 12 · 2026',hero:1},
 {big:'Now… about these two.',small:'They met. Nobody announced, “this is forever.”',fun:1},
 {big:'It was probably meant to be casual.',small:'Then one conversation somehow needed another.'},
 {big:'Then another.',small:'And suddenly “see you sometime” became “when are we meeting?”',fun:1},
 {big:'The funny thing about forever…',small:'It rarely introduces itself properly.',rose:1},
 {big:'It just keeps showing up.',small:'In laughter. In patience. In choosing each other.'},
 {big:'So they chose a date.',small:'Tuesday · 22 December 2026',hero:1},
 {big:'First, the promise.',small:'10:00 AM · St. Mary’s Cathedral Rubaga',church:1},
 {big:'With a special blessing.',small:'Holy Matrimony by His Grace Archbishop Paul Ssemogerere',church:1},
 {big:'Then… we celebrate.',small:'2:30 PM · Reception · Mutima Hall',party:1},
 {big:'Come hungry.',small:'4:00 PM · Dinner',fun:1},
 {big:'And save room.',small:'6:00 PM · Cake',fun:1},
 {big:'Bring your best smile.',small:'The rest of the evening belongs to music, family & joy.',party:1},
 {program:1}
];
function style(){if(q('#loveJourneyStyle'))return;const s=document.createElement('style');s.id='loveJourneyStyle';s.textContent=`
#fullEnvelopeLanding{position:fixed;inset:0;z-index:1000;width:100vw;height:100dvh;min-height:100svh;overflow:hidden;background:#082746;color:#f4dfb3;font-family:'DM Sans',sans-serif;perspective:1800px;isolation:isolate}#fullEnvelopeLanding:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 38%,rgba(47,96,144,.3),transparent 44%),repeating-linear-gradient(135deg,rgba(255,255,255,.02) 0 1px,transparent 1px 9px);pointer-events:none}.fe-title{position:absolute;z-index:7;top:5vh;left:5vw;right:5vw;text-align:center;transition:.65s ease;pointer-events:none}.fe-title small{font-size:9px;letter-spacing:.38em;color:#d9bb84}.fe-title h1{margin:2vh 0 1vh;font:500 clamp(44px,11vw,84px)/.86 'Cormorant Garamond',serif;color:#f7e8c9}.fe-title .rule{width:min(36vw,220px);height:1px;margin:2vh auto;background:linear-gradient(90deg,transparent,#d5b36f,transparent)}.fe-title p{margin:.5vh 0;font-size:clamp(7px,2vw,11px);letter-spacing:.28em;text-transform:uppercase;color:#e2c792}.fe-flap,.fe-left,.fe-right,.fe-bottom{position:absolute;background-image:repeating-linear-gradient(135deg,rgba(255,255,255,.018) 0 1px,transparent 1px 9px),linear-gradient(145deg,#123f70,#0a2d51 60%,#061a31);transition:transform 1.15s cubic-bezier(.16,1,.3,1),opacity .7s}.fe-flap{z-index:5;left:0;right:0;top:0;height:66%;clip-path:polygon(0 0,50% 88%,100% 0);transform-origin:50% 0;filter:drop-shadow(0 20px 28px #0005)}.fe-left{z-index:3;left:0;bottom:0;width:74%;height:67%;clip-path:polygon(0 0,100% 61%,100% 100%,0 100%)}.fe-right{z-index:3;right:0;bottom:0;width:74%;height:67%;clip-path:polygon(0 61%,100% 0,100% 100%,0 100%)}.fe-bottom{z-index:4;left:0;right:0;bottom:0;height:51%;clip-path:polygon(0 100%,50% 0,100% 100%)}.fe-seal{position:absolute;z-index:12;left:50%;top:60%;width:clamp(116px,19vw,168px);height:clamp(116px,19vw,168px);transform:translate(-50%,-50%);border-radius:50%;border:2px solid #f5d8a17a;display:grid;place-items:center;background:radial-gradient(circle at 34% 27%,#e1be76,#a97a36 36%,#76501f 64%,#4b3011);box-shadow:inset 0 0 0 8px #ffedc51c,inset 0 0 0 18px #39220b2e,0 28px 55px #0008;color:#f9e4bb;font:500 clamp(28px,4.6vw,42px) 'Cormorant Garamond',serif;letter-spacing:.08em;cursor:pointer}.fe-seal:before{content:"";position:absolute;inset:-16px;border:1px solid #e0be7f7a;border-radius:50%;animation:sealPulse 2.4s infinite}.fe-seal:after{content:"TAP TO OPEN";position:absolute;top:calc(100% + 34px);left:50%;transform:translateX(-50%);white-space:nowrap;font:600 9px 'DM Sans';letter-spacing:.35em;color:#d9bc84}@keyframes sealPulse{50%{transform:scale(1.12);opacity:.9}0%,100%{transform:scale(.95);opacity:.35}}
.opening .fe-flap{transform:rotateX(178deg)}.opening .fe-left{transform:translateX(-14%)}.opening .fe-right{transform:translateX(14%)}.opening .fe-bottom{transform:translateY(18%)}.opening .fe-seal{opacity:0;transform:translate(-50%,-50%) scale(.75)}.opening .fe-title{opacity:0;transform:translateY(-20px)}
.fe-prologue{position:absolute;inset:0;z-index:30;background:#06111b;opacity:0;pointer-events:none;transition:opacity .75s;overflow:hidden}.prologue-on .fe-prologue{opacity:1;pointer-events:auto}.fe-photo{position:absolute;inset:-5%;background:center/cover no-repeat;opacity:0;filter:saturate(.9) brightness(.42);transform:scale(1.14) translate3d(0,0,0);transition:opacity 1s ease,transform 3.5s ease,filter 1s ease}.fe-photo.show{opacity:.68;transform:scale(1.025) translate3d(var(--panx,0),var(--pany,0),0);filter:saturate(.98) brightness(.55)}.fe-photo.out{opacity:0;transform:scale(.98)}.fe-vignette{position:absolute;inset:0;z-index:3;background:radial-gradient(circle at 50% 45%,transparent 0 25%,#03090f42 57%,#03090fd9 100%)}
.fe-story{position:absolute;inset:0;z-index:8;display:grid;place-items:center;text-align:center;padding:7vh 7vw}.fe-scene{position:absolute;left:6vw;right:6vw;top:50%;transform:translateY(-48%) scale(.91);opacity:0;transition:opacity .62s,transform .9s cubic-bezier(.16,1,.3,1);text-shadow:0 8px 34px #000b}.fe-scene.show{opacity:1;transform:translateY(-50%) scale(1)}.fe-scene.hide{opacity:0;transform:translateY(-56%) scale(1.035)}.fe-scene h2{margin:0;color:#fff7e8;font:500 clamp(43px,10vw,90px)/.94 'Cormorant Garamond',serif;letter-spacing:-.025em}.fe-scene p{max-width:740px;margin:20px auto 0;color:#e1c38e;font:500 clamp(9px,2vw,14px)/1.6 'DM Sans';letter-spacing:.16em;text-transform:uppercase}.fe-scene.hero h2{font-size:clamp(58px,13vw,118px);color:#f5dfb7}.fe-scene.fun h2:after{content:" ✦";font-size:.34em;color:#d5ac72}.fe-scene.church:before{content:"✝";display:block;margin-bottom:18px;font:400 30px serif;color:#d7b477}.fe-scene.party:before{content:"✦  ✦  ✦";display:block;margin-bottom:18px;color:#d7b477;letter-spacing:.5em}
.fe-program{width:min(92vw,760px);margin:auto;padding:clamp(26px,5vw,52px);border:1px solid #d4b47866;background:#06111bc7;backdrop-filter:blur(10px);box-shadow:0 34px 90px #0007}.fe-program .pk{font:600 8px 'DM Sans';letter-spacing:.38em;color:#d4b478;text-transform:uppercase}.fe-program h2{font-size:clamp(45px,9vw,78px);margin:12px 0 22px}.fe-program-grid{border-top:1px solid #d4b47866}.fe-program-row{display:grid;grid-template-columns:minmax(92px,1fr) 2.4fr;gap:18px;padding:15px 0;border-bottom:1px solid #d4b4783d;text-align:left}.fe-program-row b{font:500 clamp(21px,4vw,34px) 'Cormorant Garamond';color:#f5dfb7}.fe-program-row span{align-self:center;font-size:clamp(8px,1.7vw,12px);letter-spacing:.1em;color:#fff9;line-height:1.5}
.fe-rose{position:absolute;z-index:7;opacity:0;color:#e1b7b1;filter:drop-shadow(0 6px 10px #0005);font-size:clamp(24px,7vw,62px);transform:scale(.1) rotate(var(--r));transition:1s cubic-bezier(.16,1,.3,1);pointer-events:none}.fe-rose:before{content:"✿"}.fe-rose.bloom{opacity:.9;transform:scale(1) rotate(var(--r))}.fe-petal{position:absolute;z-index:7;top:-5vh;color:#e9c7c1;font-size:16px;animation:petalFall var(--d) linear forwards}@keyframes petalFall{0%{opacity:0;transform:translateY(-5vh) rotate(0)}10%{opacity:.8}100%{opacity:0;transform:translate3d(var(--x),110vh,0) rotate(420deg)}}
.fe-progress{position:absolute;z-index:12;left:7vw;right:7vw;bottom:4vh;height:1px;background:#fff2}.fe-progress i{display:block;height:100%;width:0;background:linear-gradient(90deg,#d1aa73,#f3dcae);transition:width .4s}.fe-counter{position:absolute;z-index:12;right:7vw;bottom:5.2vh;font:500 7px 'DM Sans';letter-spacing:.25em;color:#fff7}.leaving{opacity:0!important;transform:scale(1.025);transition:opacity .9s,transform 1.1s;pointer-events:none!important}
@media(max-width:500px){.fe-title{top:3.5vh}.fe-title h1{font-size:43px}.fe-title p{font-size:7px}.fe-seal{top:61%;width:112px;height:112px;font-size:29px}.fe-scene{left:5vw;right:5vw}.fe-scene h2{font-size:43px}.fe-scene.hero h2{font-size:64px}.fe-program{padding:24px 20px}.fe-program-row{grid-template-columns:95px 1fr;gap:10px;padding:12px 0}.fe-program-row b{font-size:25px}}
@media(prefers-reduced-motion:reduce){.fe-photo,.fe-scene,.fe-flap,.fe-left,.fe-right,.fe-bottom{transition-duration:.2s!important}.fe-rose,.fe-petal{display:none!important}}
`;document.head.appendChild(s)}
function bloom(layer){for(let i=0;i<18;i++){const r=document.createElement('span');r.className='fe-rose';r.style.left=(Math.random()*96-2)+'vw';r.style.top=(4+Math.random()*88)+'vh';r.style.setProperty('--r',(Math.random()*80-40)+'deg');layer.appendChild(r);setTimeout(()=>r.classList.add('bloom'),i*45);setTimeout(()=>r.remove(),3600)}for(let i=0;i<20;i++){const p=document.createElement('span');p.className='fe-petal';p.textContent='•';p.style.left=Math.random()*100+'vw';p.style.setProperty('--x',(Math.random()*150-75)+'px');p.style.setProperty('--d',(3.3+Math.random()*2)+'s');p.style.animationDelay=Math.random()*.8+'s';layer.appendChild(p);setTimeout(()=>p.remove(),6000)}}
function installLanding(){if(q('#fullEnvelopeLanding'))return;style();const l=document.createElement('div');l.id='fullEnvelopeLanding';l.innerHTML=`<div class="fe-title"><small>A PRIVATE INVITATION</small><h1>Dr Martin &amp; Pearl</h1><div class="rule"></div><p>Some things are simply meant to be</p><p>Love · Faith · A Beautiful Future</p></div><div class="fe-flap"></div><div class="fe-left"></div><div class="fe-right"></div><div class="fe-bottom"></div><button class="fe-seal" aria-label="Open invitation">M&amp;P</button><div class="fe-prologue"><div class="fe-photos"></div><div class="fe-vignette"></div><div class="fe-story"></div><div class="fe-roses"></div><div class="fe-progress"><i></i></div><div class="fe-counter"></div></div>`;document.body.appendChild(l);
 const photos=q('.fe-photos',l),story=q('.fe-story',l),roses=q('.fe-roses',l),counter=q('.fe-counter',l),prog=q('.fe-progress i',l);DRIVE_IDS.forEach((id,i)=>{const d=document.createElement('div');d.className='fe-photo';d.style.backgroundImage=`url("${drive(id)}")`;d.style.setProperty('--panx',((i%3)-1)*1.8+'%');d.style.setProperty('--pany',((i%2)?-1.3:1.2)+'%');photos.appendChild(d)});scenes.forEach((sc,i)=>{const d=document.createElement('section');d.className='fe-scene'+(sc.hero?' hero':'')+(sc.fun?' fun':'')+(sc.church?' church':'')+(sc.party?' party':'');if(sc.program)d.innerHTML=`<div class="fe-program"><div class="pk">THE WEDDING DAY</div><h2>Our Programme</h2><div class="fe-program-grid"><div class="fe-program-row"><b>10:00 AM</b><span>Holy Matrimony · St. Mary’s Cathedral Rubaga<br>By His Grace Archbishop Paul Ssemogerere</span></div><div class="fe-program-row"><b>2:30 PM</b><span>Reception · Mutima Hall · Nican Resort Hotel, Katale Seguku</span></div><div class="fe-program-row"><b>4:00 PM</b><span>Dinner</span></div><div class="fe-program-row"><b>6:00 PM</b><span>Cake</span></div></div></div>`;else d.innerHTML=`<h2>${sc.big}</h2><p>${sc.small}</p>`;story.appendChild(d)});
 const ps=qa('.fe-photo',l),ss=qa('.fe-scene',l);let timers=[];const later=(f,m)=>{const t=setTimeout(f,m);timers.push(t)};function showScene(i){ss.forEach((x,j)=>{x.classList.toggle('show',j===i);x.classList.toggle('hide',j<i)});ps.forEach((x,j)=>{const target=j===i%ps.length;x.classList.toggle('show',target);if(!target&&x.classList.contains('show'))x.classList.add('out')});if(ps.length){const p=ps[i%ps.length];p.classList.remove('out');p.classList.add('show')}if(scenes[i]?.rose)bloom(roses);counter.textContent=`${String(i+1).padStart(2,'0')} / ${String(scenes.length).padStart(2,'0')}`;prog.style.width=((i+1)/scenes.length*100)+'%'}
 q('.fe-seal',l).addEventListener('click',()=>{l.classList.add('opening');const under=q('.intro .seal');if(under)under.click();later(()=>l.classList.add('prologue-on'),720);const HOLD=3200;scenes.forEach((_,i)=>later(()=>showScene(i),1100+i*HOLD));later(()=>{l.classList.add('leaving');const intro=q('.intro');if(intro){intro.style.display='none';intro.remove()}document.body.classList.remove('lock');const site=q('.site');if(site)site.classList.add('ready');scrollTo(0,0)},1100+scenes.length*HOLD+800);later(()=>l.remove(),1100+scenes.length*HOLD+1900)},{once:true})}
function installBook(){const pages=qa('.chapter').slice(0,5);if(!pages.length||q('#storybook'))return;const book=document.createElement('div');book.className='storybook';book.id='storybook';pages[0].parentNode.insertBefore(book,pages[0]);pages.forEach((page,i)=>{page.classList.add('book-page');page.dataset.page=i;if(i===2)page.classList.add('focus-top');const edge=document.createElement('div');edge.className='page-edge';const num=document.createElement('div');num.className='page-number';num.textContent=`0${i+1} / 05`;page.append(edge,num);book.appendChild(page)});let raf=0;const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));function turn(){raf=0;const top=book.offsetTop,vh=innerHeight;pages.forEach((page,i)=>{const p=clamp((scrollY-(top+i*vh))/vh,0,1),e=1-Math.pow(1-p,2.55);page.style.zIndex=60-i;page.style.transform=`translate3d(0,${-Math.sin(p*Math.PI)*16}px,0) rotateY(${-178*e}deg) scale(${1-Math.sin(p*Math.PI)*.018})`;page.style.filter=`brightness(${1-p*.17})`;page.classList.toggle('turning',p>.04&&p<.96)})}const schedule=()=>{if(!raf)raf=requestAnimationFrame(turn)};addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);turn()}
installLanding();installBook();
})();